#! /bin/sh

apm install emmet
apm install autoprefixer
apm install color-picker
apm install linter
apm install autocomplete-paths
apm install atom-beautify
apm install expose
apm install vim-mode
apm install seti-syntax
apm install atom-material-ui
apm install atom-material-syntax
apm install monokai
apm install lucario
apm install markdown-preview
apm install javascript-snippets
apm install docblockr
apm install terminal-plus
apm install graphite-ui
apm install autocomplete-plus
apm install autocomplete-snippets
apm install git-diff
apm install atom-beautify
apm install git-blame
apm install git-log
apm install merge-conflicts
apm install go-format
apm install highlight-selected
apm install indent-helper
apm install livereload
apm install autocomplete-python
apm install autocomplete-css
apm install file-icons
apm install filetype-color
apm install atom-html-preview
apm install csscomb
apm install atom-ternjs
apm install python-tools
apm install language-shellscript
apm install react
apm install python-indent
